import 'package:flutter/material.dart';
import 'package:udemy_hotel/models/category.dart';
import 'package:udemy_hotel/models/meals.dart';

const Dummy_Data = const [
  Category(
    id: 'c1',
    title: 'Neplease',
    colors: Colors.red,
  ),
  Category(
    id: 'c2',
    title: 'italian',
    colors: Colors.pink,
  ),
  Category(
    id: 'c3',
    title: 'indain',
    colors: Colors.cyan,
  ),
  Category(
    id: 'c4',
    title: 'chinease',
    colors: Colors.teal,
  ),
  Category(
    id: 'c5',
    title: 'korean',
    colors: Colors.deepOrange,
  ),
  Category(
    id: 'c6',
    title: 'thai food',
    colors: Colors.deepOrangeAccent,
  ),
  Category(
    id: 'c6',
    title: 'arabi',
    colors: Colors.amber,
  ),
];
const Dummy_Meals = const [
  Meals(
    id: 'm0',
    title: 'Daal Bhat',
    categories: [
      'c1',
    ],
    ingredients: [
      'Rice',
      'vegetable',
      'meat',
    ],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://www.intrepidtravel.com/adventures/wp-content/uploads/2017/10/shutterstock_581449438-e1506922146561.jpg",
    duration: 45,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: true,
    isLactosFree: false,
    isVegeterian: false,
  ),
  Meals(
    id: 'm1',
    title: 'Momo',
    categories: ['c1', 'c2', 'c6'],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://c.ndtvimg.com/2020-01/2brioi88_momos_625x300_21_January_20.jpg",
    duration: 15,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: true,
    isLactosFree: false,
    isVegeterian: false,
  ),
  Meals(
    id: 'm2',
    title: ' Chowmin ',
    categories: ['c1', 'c2'],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://c.ndtvimg.com/2020-04/3hfomiho_chowmein_625x300_20_April_20.jpg",
    duration: 10,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactosFree: false,
    isVegeterian: false,
  ),
  Meals(
    id: 'm3',
    title: ' Sizzler',
    categories: ['c2', 'c4'],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://vaya.in/recipes/wp-content/uploads/2019/01/Chicken-Sizzler.jpg",
    duration: 30,
    complexity: Complexity.hard,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactosFree: false,
    isVegeterian: false,
  ),
  Meals(
    id: 'm4',
    title: 'Pizza',
    categories: [
      'c2',
      'c4',
      'c5',
    ],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://static.toiimg.com/photo/53110049.cms",
    duration: 35,
    complexity: Complexity.challenging,
    affordability: Affordability.pricey,
    isGlutenFree: false,
    isLactosFree: false,
    isVegeterian: false,
  ),
  Meals(
    id: 'm5',
    title: 'Burger',
    categories: ['c2', 'c4', 'c3'],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://english.onlinekhabar.com/wp-content/uploads/2018/09/Hand-Made-Burger-2.jpg",
    duration: 19,
    complexity: Complexity.hard,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactosFree: false,
    isVegeterian: true,
  ),
  Meals(
    id: 'm6',
    title: ' Naan',
    categories: [
      'c2',
    ],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://static.toiimg.com/thumb/53338316.cms?imgsize=223266&width=800&height=800",
    duration: 10,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactosFree: true,
    isVegeterian: true,
  ),
  Meals(
    id: 'm7',
    title: ' Kimchi',
    categories: [
      'c5',
    ],
    ingredients: ['salt', 'soda', 'wheat', 'powder'],
    steps: [
      'To make the stuffing, heat the oil in a pan on medium heat-high heat. Once hot add ginger and garlic.',
      'Saute for 30 seconds. Make sure not to burn them.' 'Now add chopped veggies (onion, cabbage, carrot, capsicum).',
      'Mix and continue cooking with stirring constantly for 3-4 minutes.',
      'Again mix and cook for 2 minutes. Be careful not to overcook the vegetables, we do not want them mushy.',
      'Similarly shape all of them. If you do not want to spend time in shaping, you can just make half moon shape like gujiya and then combine both edges together. It looks something similar to wontons (aka flower bud or nurse cap shape).',
    ],
    imgurl: "https://lh3.googleusercontent.com/proxy/KiR6K4YT29-EBcZ8gNLs6AoEJNDvL0be6MlFNqlZKIyv53Q9EY3cUF3ddM-frkboS-_xQMSDji_7SdJneMVYy6pu8a8C-g1JtFSB",
    duration: 65,
    complexity: Complexity.simple,
    affordability: Affordability.affordable,
    isGlutenFree: false,
    isLactosFree: false,
    isVegeterian: false,
  ),
];
